Transform dialect generic no mvars
opencompl/ssa pull request #128
Opened 2023-10-31 12:27 UTC by bollu

We generalize the ability to convert generic MLIR syntax into `Com/Expr`.

2023-11-14 14:21 UTC, alexkeizer commented
It *should* be fine to merge, but I think we should first test that it actually works by also giving an instance for another dialect, say the SimpleIR example.

2023-11-15 01:10 UTC, bollu commented
This does not yet work, in the file `AliveAutoGenerated.lean`, we see the error:
Translation failed to reduce, possibly too generic syntax
```
        . 'error Except.ok
  {
    fst :=
      [InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w), InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w),
        InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w)],
    snd :=
      { fst := InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w),
        snd :=
          Com.lete
            (Expr.mk (InstCombine.MOp.not (ConcreteOrMVar.concrete w)) _
              (HVector.cons { val := 2, property := _ } HVector.nil) HVector.nil)
   ...
  }
```

which is very bizarre, because it sees that the head term is `Except.ok`!

@alexkeizer Do you know why this happens? For whatever reason, the QQ match to `Except.ok` does no go through :(

2023-11-15 05:05 UTC, bollu commented
I made progress by replacing the Qq match with a raw `Expr` match. This now leaves us with the error:

> ./././SSA/Projects/InstCombine/AliveAutoGenerated.lean:31:4: error: code generator does not support recursor 'InstCombine.MOp.rec' yet, consider using 'match ... with' and/or structural recursion
> ./././SSA/Projects/InstCombine/AliveAutoGenerated.lean:42:4: error: code generator does not support recursor 'InstCombine.MOp.rec' yet, consider using 'match ... with' and/or structural recursion

---- 

```
./././SSA/Projects/InstCombine/AliveAutoGenerated.lean:54:41: error: type mismatch
  _
has type
  HEq ?m.273585 ?m.273585 : Prop
but is expected to have type
  ⟦?m.270983⟧ = Option ?m.270984 : Prop
./././SSA/Projects/InstCombine/AliveAutoGenerated.lean:54:68: error: application type mismatch
  ?m.271475 ⊑ alive_AddSub_1043_tgt w
argument
  alive_AddSub_1043_tgt w
has type
  @Com (InstCombine.MOp 0) (InstCombine.MTy 0)
    {
      signature := fun op =>
        {
          sig :=
            (fun {φ} motive x h_1 h_2 h_3 h_4 h_5 h_6 h_7 h_8 h_9 h_10 h_11 h_12 h_13 h_14 h_15 h_16 h_17 h_18 h_19 =>
                InstCombine.MOp.rec (fun w => h_1 w) (fun w => h_2 w) (fun w => h_15 w) (fun w => h_3 w)
                  (fun w => h_4 w) (fun w => h_5 w) (fun w => h_6 w) (fun w => h_13 w) (fun w => h_12 w)
                  (fun w => h_18 w) (fun w => h_7 w) (fun w => h_8 w) (fun w => h_9 w) (fun w => h_16 w)
                  (fun w => h_17 w) (fun w => h_11 w) (fun w => h_10 w) (fun c w => h_14 c w) (fun w val => h_19 w val)
                  x)
              (fun x => List (InstCombine.MTy 0)) op (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w])
              (fun c w => [InstCombine.MTy.bitvec w, InstCombine.MTy.bitvec w]) (fun w => [InstCombine.MTy.bitvec w])
              (fun w => [InstCombine.MTy.bitvec w]) (fun w => [InstCombine.MTy.bitvec w])
              (fun w =>
                [InstCombine.MTy.bitvec (ConcreteOrMVar.concrete 1), InstCombine.MTy.bitvec w,
                  InstCombine.MTy.bitvec w])
              fun w val => [],
          regSig := [],
          outTy :=
            (fun {φ} motive x h_1 h_2 h_3 h_4 h_5 h_6 h_7 h_8 h_9 h_10 h_11 h_12 h_13 h_14 h_15 h_16 h_17 h_18 h_19 =>
                InstCombine.MOp.rec (fun w => h_1 w) (fun w => h_2 w) (fun w => h_3 w) (fun w => h_4 w) (fun w => h_5 w)
                  (fun w => h_6 w) (fun w => h_7 w) (fun w => h_17 w) (fun w => h_16 w) (fun w => h_9 w)
                  (fun w => h_12 w) (fun w => h_13 w) (fun w => h_8 w) (fun w => h_10 w) (fun w => h_11 w)
                  (fun w => h_14 w) (fun w => h_15 w) (fun c w => h_18 c w) (fun w val => h_19 w val) x)
              (fun x => InstCombine.MTy 0) op (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun w => InstCombine.MTy.bitvec w)
              (fun w => InstCombine.MTy.bitvec w) (fun c w => InstCombine.MTy.bitvec (ConcreteOrMVar.concrete 1))
              fun width val => InstCombine.MTy.bitvec width } }
    [InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w), InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w),
      InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w)]
    (InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w)) : Type
but is expected to have type
  @Com (InstCombine.MOp 0) (InstCombine.MTy 0) InstCombine.instOpSignatureMOpMTy
    [InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w), InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w),
      InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w)]
    (InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w)) : Type
```

It seems that we implicitly make use of the recursor somewhere on the `InstCombine.MOp`

2023-11-15 05:07 UTC, bollu commented
Cool, changing `reduceAll` to `reduce` fixes (?) this!

2023-11-15 06:48 UTC, bollu commented
I'm now trying to get a managable `simp` set for `Alive`.

2023-11-15 07:25 UTC, bollu commented
@alexkeizer if you could take a look at making the full generic infrastructure produces terms that we can reduce in sensible time, that would be super =)

2023-11-15 08:18 UTC, bollu commented
@alexkeizer Actually, I would suggest doing the following:

(1) we still keep a copy of the old hardcoded translation, which we use for `Alive`.
(2) we use the new transform framework for our other IRs, that don't make use of metavariables. For example, the `SimpleIR` gets simplified no problem by `simp_peephole`. Wild conjecture: maybe it's the metavar translation creates lots of complex terms.

2023-11-20 14:30 UTC, alexkeizer requested changes
This PR has become quite messy as part of the deadline sprint. I'd suggest we clean it up a bit before merging, now that the deadline-related time pressure is gone

2023-11-20 14:34 UTC, alexkeizer commented
> This does not yet work, in the file `AliveAutoGenerated.lean`, we see the error: Translation failed to reduce, possibly too generic syntax
> 
> ```
>         . 'error Except.ok
>   {
>     fst :=
>       [InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w), InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w),
>         InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w)],
>     snd :=
>       { fst := InstCombine.MTy.bitvec (ConcreteOrMVar.concrete w),
>         snd :=
>           Com.lete
>             (Expr.mk (InstCombine.MOp.not (ConcreteOrMVar.concrete w)) _
>               (HVector.cons { val := 2, property := _ } HVector.nil) HVector.nil)
>    ...
>   }
> ```
> 
> which is very bizarre, because it sees that the head term is `Except.ok`!
> 
> @alexkeizer Do you know why this happens? For whatever reason, the QQ match to `Except.ok` does no go through :(

I don't know exactly what's happening here, but I vaguely recall a similar issue where the term seemed to be an `Except.ok`, but scrolling down the huge term later revealed the `Except.ok` was an argument to a `bind` that somehow refused to reduce. I think there was a recursor involved as well.

2023-12-08 04:52 UTC, bollu commented on SSA/Projects/InstCombine/LLVM/EDSL.lean
> + | .bitvec w =>
Interesting, I actually prefer them being in the same file, so the feature of "elaboration" is conslolidated.

2023-12-08 05:02 UTC, bollu commented on SSA/Projects/InstCombine/LLVM/EDSL.lean
> + | .bitvec w =>
To be more precise, I dislike having too many files, as it splinters the codebase. In this case, I find that `EDSL` is a well-scoped feature, and all the code that goes into implementing the EDSL (the instance of `TransformDialect` and the related meta-code) lives in a single file. Thus, I would advocate for keeping it as-is.

2024-01-08 17:14 UTC, alexkeizer commented on SSA/Projects/InstCombine/Alive.lean
> +import SSA.Projects.InstCombine.AliveAutoGenerated
Can we make this part of a separate build facet, so that local builds don't have to include it, but we can run the whole file on CI?

2024-01-09 13:12 UTC, alexkeizer approved these changes
There is one cleanup I'll adress, the rest of my comments are OK to put in a post-merge issue. LGTM otherwise!

2024-01-09 13:12 UTC, alexkeizer commented on SSA/Core/Framework.lean
> +      ] -- separate `simp` block so it does not fail if MLIR.AST is not open.
I think is resolved now

2024-01-09 13:12 UTC, alexkeizer commented on SSA/Core/Framework.lean
> +        DialectMorphism.mapOp, DialectMorphism.mapTy,
There's some duplication in the simp-set here (just making a note, I'll address it)

2024-01-09 13:12 UTC, alexkeizer commented on SSA/Projects/InstCombine/LLVM/EDSL.lean
> +      ⟩
This looks like it could use some extra abstraction / deduplication. Let's defer that to a separate, low-prio issue

2024-01-09 16:49 UTC, alexkeizer commented on SSA/Core/Framework.lean
> +   )
This seems to have been resolved by removing the `_mlir` macro

2024-01-10 21:41 UTC, merged