Generalize to arbitrary variable counts
opencompl/ssa pull request #224
Opened 2024-04-12 07:13 UTC by tobiasgrosser

2024-04-12 07:46 UTC, tobiasgrosser commented on SSA/Core/Tactic.lean
> +      repeat (generalize_or_fail at $ll)
This already supports an arbitrary number of generalizations, but I am unsure how to revert an arbitrary number of variables. Anyone has an idea?

2024-04-12 12:30 UTC, tobiasgrosser commented on SSA/Core/Tactic.lean
> +      repeat (generalize_or_fail at $ll)
This now works as I figured out how to revert a variable of a given type.

2024-04-12 14:02 UTC, alexkeizer requested changes
Looking at line 304 (definition `p1`) of PaperExamples, the goal state post `simp-peephole` is
```
Γv : Ctxt.Valuation [Ty.int]
⊢ (fun v => v + v)^[0] (Γv { val := 0, property := ⋯ }) = Γv { val := 0, property := ⋯ }
```
whereas on the main branch, the goal is
```
⊢ ∀ (a : BitVec 32), (fun v => v + v)^[0] a = a
```

So it seems the refactor doesn't work 100% as intended, even if it doesn't break the build

2024-04-12 14:09 UTC, tobiasgrosser commented on SSA/Core/Tactic.lean
> +        conv in ($ll { val := (_ : Nat), property := _ }) => skip;
I added a comment. Thank you for bringing this up.

2024-04-12 14:09 UTC, tobiasgrosser commented on SSA/Core/Tactic.lean
> +      repeat(revert ‹TyDenote.toType _›)
Great idea. I now revert immediately.

2024-04-12 14:38 UTC, tobiasgrosser commented
> Looking at line 304 (definition `p1`) of PaperExamples, the goal state post `simp-peephole` is
> 
> ```
> Γv : Ctxt.Valuation [Ty.int]
> ⊢ (fun v => v + v)^[0] (Γv { val := 0, property := ⋯ }) = Γv { val := 0, property := ⋯ }
> ```
> 
> whereas on the main branch, the goal is
> 
> ```
> ⊢ ∀ (a : BitVec 32), (fun v => v + v)^[0] a = a
> ```
> 
> So it seems the refactor doesn't work 100% as intended, even if it doesn't break the build. We might want to remove the `try` in `try revert $ll`, so that such failures to remove the local context become errors (with a configuration to turn this behaviour of)

The problem is described here: https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/conv.20tactic.20sometimes.20solves.20goal/near/432918099

2024-04-12 14:46 UTC, alexkeizer commented
> In brief the check if a pattern exits seems to solve trivial pattern and consequently prevents later leads to a failure of 'no goals to be solved' which then prevents the simplification we are after.

You could similarly guard the later tactics with a `first | done | ...`, that way won't prevent the closing of trivial goals, but it will prevent further 'no goals to be solved' errors. We already close some trivial goals with the `simp`-call, so I don't think that's so bad

2024-04-12 14:48 UTC, tobiasgrosser commented
> ```
> first
>   | done
>   | simp (config := {failIfUnchanged := false}) only [Ctxt.Var.toSnoc, Ctxt.Var.last]
>      repeat (generalize_or_fail at $ll)
>      clear $ll
> ```

This breaks ScfFunctor.lean

2024-04-12 14:52 UTC, alexkeizer commented
Ah, yeah it breaks `ScfFunctor` on main as well (I was just double checking my claim): we do apply the context, but only to a variable `v : Var ..` in the context, not an instance of `Var.mk _ _`, which is what we check for in generalize.

2024-04-12 14:57 UTC, tobiasgrosser commented
> > In brief the check if a pattern exits seems to solve trivial pattern and consequently prevents later leads to a failure of 'no goals to be solved' which then prevents the simplification we are after.
> 
> You could similarly guard the later tactics with a `first | done | ...`, that way won't prevent the closing of trivial goals, but it will prevent further 'no goals to be solved' errors. We already close some trivial goals with the `simp`-call, so I don't think that's so bad

I dropped this for now. I feel this is the best we can do so far. Or would you like to see further changes.

Btw, lean3 had a tactic that failed if a child-tactic succeeded and the other way around. Do these still exist under a different name?

2024-04-12 15:00 UTC, alexkeizer commented
I'm having a go at it now, we can just generalize the `generalize` line to work for all kinds of variables.
Since the `repeat (generalize_or_fail)` line may close the goal, we do need to add another layer of `first | done | ...` after it.

2024-04-12 16:03 UTC, alexkeizer commented
So this change also breaks two proof in `AliveAutoGenerated`, where the context fails to clear.
Turns out, this failure also happens on main, we just don't notice there because the error is swallowed by `try`, and the rest of the proof is sorried out. IMO more evidence for why we *shouldn't* use `try`

2024-04-12 16:13 UTC, tobiasgrosser commented
contains? is broken in our codebase:

https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/conv.20tactic.20sometimes.20solves.20goal/near/432918099

2024-04-13 04:30 UTC, tobiasgrosser commented
> > So this change also breaks two proof in `AliveAutoGenerated`, where the context fails to clear. Turns out, this failure also happens on main, we just don't notice there because the error is swallowed by `try`, and the rest of the proof is sorried out. IMO more evidence for why we _shouldn't_ use `try`
> 
> Follow-up on this: the issue seems to be that the goal still mentions `Ctxt.Valuation.snoc \Gammav ... \<0, ...\>`. This _should_ reduce to `\Gammav \<0, ...\>`, but it isn't. I tried debugging it, but couldn't figure it out, and am not super keen to go too deep on this. Since it's already broken in `main` anyway, I've just moved the `sorry` up in the two affected theorems (`alive_Select_858` and `alive_Select_859`)

Thank you for investigating. We should get this fixed eventually, but I don't think we need to add this to this PR.

2024-04-15 13:46 UTC, tobiasgrosser commented on SSA/Core/Tactic.lean
> +        revert e
> Does this still have the issue that it sometimes closes a trivial goal?
> 
> Some testing suggests it doesn't, so I've added a commit that replaces `first | done | clear $ll` with just `clear $ll` below
Thank you. This is great.

2024-04-15 13:49 UTC, tobiasgrosser commented
I squashed your change. Is there anything else you want me to change, or can we merge this?

2024-04-15 13:57 UTC, alexkeizer commented
I also removed the now-obsolete comment about needing `first | done | clear _`.
With this, I think it's good, feel free to squash and merge

2024-04-15 14:16 UTC, tobiasgrosser commented
@alexkeizer, I think you need to approve this PR (and drop your merge-requested).

2024-04-15 15:21 UTC, merged